blog/urls.py
from unicodedata import name
from django.urls import path
from . import views

# Configuramos app_name e o atributo name de path para não termos problemas com rotas semelhantes em apps diferentes
# path() conecta uma rota a uma view
#   Primeiro parametro -> rota ou variável da rota
#   Segundo paramentro -> view a ser carregada
#   Terceiro parametro -> explicado no primeiro comentário

# O parametro <slug:slug> indica que uma variável slug deve ser carregada e essa variável corresponde ao campo slug do nosso model

app_name = "blog"

urlpatterns = [
    path("", views.ListPostView.as_view(), name="list"),
    path("post/", views.CreatePostView, name="post"),
    path("<slug:slug>/", views.DetailPostView.as_view(), name="detail")
]

tutorialdjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),
    # all auth
    path('accounts/', include("allauth.urls")),
    # my apps
    path('blog/', include("blog.urls", namespace="blog")),
    path('', include("users.urls", namespace="users"))
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home")
]

blog/models.py
from users.models import User
from django.db import models
from django.urls import reverse

# Models em Django se assemelham à Entitys em Spring Boot
# A classse models.Model tem sua dependência injetada para que seja registrada como um modelo no sistema
# O nosso modelo é composto pelos campos da tabela desejada


class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    # Relacionamentos são feitos através do método ForeignKey, recebendo o modelo referenciado como primeiro parâmetro
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    # A função __str__ tem o self injetado em sua declaração e funciona para trocar o nome que representa cada instância deste modelo
    def __str__(self):
        return self.title

    # A função getDetailPath utiliza a função reverse() do django para gerar a url absoluta referente ao nosso app
    # Passamos o argumento slug para que ele incremente à url o valor de slug do nosso modelo
    def getDetailPath(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# É interessante a criação de um modelo próprio de usuário para que você tenha controle e possa atualizá-lo conforme as necessidades do projeto
# Inicialmente o seu Usuário vai ser uma pura extensão do AbstractUser do Django (que já existe e já é bem completo), mas ao criar seu próprio modelo, você fica no controle das possiveis mudanças
# Aqui, por exemplo, adicionamos o campo bio para que nosso usuário personalizado possua uma biografia


class User(AbstractUser):
    bio = models.TextField(blank=True)

blog/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "slug", "author", "body"]

users/forms.py
from django.contrib.auth import forms
from .models import User

# Além do usuário personalizado, também criamos formulário personalizados
# Novamente, a única diferença entre as nossas classes e as originais do Django são o modelo referenciado, aqui indicamos o nosso model de Usuário (que possue bio)
# Assim como em User, criamos nossas próprias classes de form para que possamos ter liberdade de incrementalas com features novas, caso necessário
# Por enquanto elas ainda funcionam exatamente iguais à suas classes pais


class UserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from .models import Post
from .forms import PostForm

# Aqui utilizamos views genéricas para agilizar a criação das nossas views básicas de listagem e detalhamento
# As views genéricas se baseiam no modelo MVT, ou seja, elas naturalmente irão requisitar um template HTML para retornar seus valores
# As views em Django são bem semelhantes aos COntrollers de SpringBoot e irão mapear as nossas rotas, recebendo requests e retornando responses
# Podemos estruturar as views em classes ou funções, próximo projeto -> estruturar views em funções e fazer elas retornarem JSON (API REST)


class ListPostView(ListView):
    model = Post


class DetailPostView(DetailView):
    model = Post

def CreatePostView(request):
    if request.method == "POST":
        newPostForm = PostForm(request.POST)
        if newPostForm.is_valid():
            newPost = newPostForm.save()
            if newPost:
                return HttpResponseRedirect('/blog')
    else:
        newPostForm = PostForm()

    return render(request, "post_form.html", {"form": newPostForm})

users/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"
        

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}
<div id="post">
    <h2> {{post.title}} </h2>
    <p> Publicado em {{post.created}} por {{post.author}} </p>
    {{post.body|linebreaks}}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'users:home' %}">Blog Python</a>
                <ul class="navbar-nav">
                    {% block navlinks %}
                    {% endblock %}
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>

templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}
<div id="post">
    <h2> {{post.title}} </h2>
    <p> Publicado em {{post.created}} por {{post.author}} </p>
    {{post.body|linebreaks}}
</div>
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Criar Post {% endblock %}

{% block content %}
    <h2> Novo Post </h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit"> Publicar </button>
    </form>
{% endblock %}

templates/blog/post_list.html
<!-- Para poder utilizar o modelo criato anteriormente, utilizamos o bloco extends referenciando o arquivo -->
{% extends "base.html" %}

{% block title %} Django's Blog 🐍 {% endblock %}

{% block navlinks %} 
    <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:post' %}">Novo Post</a>
    </li> 
{% endblock %}

<!-- Além de criar blocos nomeados de conteúdo, possível também executar funções como o loop for -->
<!-- Variável post_list foi criada pelo Generic ListView do Django, que utilizamos para criar nossa View -->
<!-- Esta vaeiável contém uma lista com todos os posts e seus campos -->
{% block content %}
    <header>
        <h1>
            Feed Principal
        </h1>
    </header>
    {% for post in post_list %}
        <div class="card">
            <h3><a href="{{post.getDetailPath}}"> {{post.title}} </a></h3>
            <small> Publicado em {{post.created}} por {{post.author}} </small>
            <p>{{post.body|linebreaks|truncatewords:10}}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %} Blog Python 🐍 {% endblock %}

{% block content %}
<div id="disconnected-message">
    <h1> Você está deslogado! </h1><br><br>
    <h2> <span> <a href="{% url 'account_login' %}"> Efetue login </a> </span> ou <span> <a href="{% url 'account_signup' %}"> cadastre-se </a> </span> para ter acesso aos posts do blog. </h2>
</div>
{% endblock %}